In [29]:
from superai.rnn.rnn_model import RNN_MODEL
import numpy as np
from common import convert_to_one_hot


print(np.array([[1], [2], [2]]).reshape(-1))


[1 2 2]


In [20]:
data = open('train_data/dinos.txt', 'r').read()
data= data.lower()
chars = list(set(data))
data_size, vocab_size = len(data), len(chars)
print('There are %d total characters and %d unique characters in your data.' % (data_size, vocab_size))

char_to_ix = { ch:i for i,ch in enumerate(sorted(chars)) }
ix_to_char = { i:ch for i,ch in enumerate(sorted(chars)) }
with open("train_data/dinos.txt") as f:
    examples = f.readlines()
examples = [x.lower().strip() for x in examples]
X = []
Y = []
count = len(examples)
for j in range(count):
    x_j = [0] + [char_to_ix[ch] for ch in examples[j]] 
    y_j = x_j[1:] + [char_to_ix["\n"]]
    print(np.array(x_j).reshape(-1))
    x = convert_to_one_hot(np.array(x_j), 27)
    x[0, 0] = 0
    y = convert_to_one_hot(np.array(y_j), 27)
    X.append(x)
    Y.append(y)

# you can select normal or lstm type
model = RNN_MODEL(27, 27, 50, "normal", 6)
for i in range(40000):
    x, y = X[i % count], Y[i % count]
    loss = model.train(x, y)
    if i % 1000 == 0:
        print("iteration{0}  cost:{1}".format(i, loss))
for i in range(10):
    indices = model.sample(char_to_ix["\n"], i+6)
    chars = [ix_to_char[idx] for idx in indices]
    print(''.join(chars[:-1]))

There are 19909 total characters and 27 unique characters in your data.
[ 0  1  1  3  8  5 14 15 19  1 21 18 21 19]
[ 0  1  1 18  4 15 14 25 24]
[ 0  1  2  4  1 12 12  1  8 19  1 21 18 21 19]
[ 0  1  2  5 12  9 19  1 21 18 21 19]
[ 0  1  2 18  9  3 20 15 19  1 21 18 21 19]
[ 0  1  2 18 15 19  1 21 18 21 19]
[ 0  1  2 25  4 15 19  1 21 18 21 19]
[ 0  1  3  1 14 20  8 15 16  8 15 12  9 19]
[ 0  1  3  8  5 12 15 21 19  1 21 18 21 19]
[ 0  1  3  8  5 18 15 18  1 16 20 15 18]
[ 0  1  3  8  9 12 12  5 19  1 21 18 21 19]
[ 0  1  3  8  9 12 12 15  2  1 20 15 18]
[ 0  1  3 18  9 19 20  1 22 21 19]
[ 0  1  3 18 15  3  1 14 20  8 15 19  1 21 18 21 19]
[ 0  1  3 18 15 20  8 15 12 21 19]
[ 0  1  3 20  9 15 19  1 21 18 21 19]
[ 0  1  4  1 13  1 14 20  9 19  1 21 18 21 19]
[ 0  1  4  1 19  1 21 18 21 19]
[ 0  1  4  5 12 15 12 15 16  8 21 19]
[ 0  1  4  5 15 16  1 16 16 15 19  1 21 18 21 19]
[ 0  1  5  7 25 16 20 15 19  1 21 18 21 19]
[ 0  1  5 15 12 15 19  1 21 18 21 19]
[ 0  1  5 16  9 19  1 21 18 2

 18 21 19]
[ 0 12 15  8 21  5  3 15 20  9 20  1 14]
[ 0 12 15 14  3 15 19  1 21 18 21 19]
[ 0 12 15 14  7  9 19 17 21  1 13  1]
[ 0 12 15 14  7 15 19  1 21 18 21 19]
[ 0 12 15 16  8 15 18  8 15 20  8 15 14]
[ 0 12 15 16  8 15 19 20 18 15 16  8  5 21 19]
[ 0 12 15 18  9  3  1 20 15 19  1 21 18 21 19]
[ 0 12 15 18  9  3 15 19  1 21 18 21 19]
[ 0 12 15 19  9 12 12  1 19  1 21 18 21 19]
[ 0 12 15 21 18  9 14  8  1 14 15 19  1 21 18 21 19]
[ 0 12 15 21 18  9 14  8  1 19  1 21 18 21 19]
[ 0 12 21  1 14  3  8 21  1 14 18  1 16 20 15 18]
[ 0 12 21  1 14 16  9 14  7 15 19  1 21 18 21 19]
[ 0 12 21  3  9  1 14 15 19  1 21 18 21 19]
[ 0 12 21  3  9  1 14 15 22  5 14  1 20 15 18]
[ 0 12 21  6  5 14  7 15 19  1 21 18 21 19]
[ 0 12 21 11 15 21 19  1 21 18 21 19]
[ 0 12 21 15 25  1 14  7  7  9  1]
[ 0 12 21 18  4 21 19  1 21 18 21 19]
[ 0 12 21 19  9 20  1 14 15 19  1 21 18 21 19]
[ 0 12 21 19 15 20  9 20  1 14]
[ 0 12 25  3 15 18  8  9 14 21 19]
[ 0 12 25 20  8 18 15 14  1 24]
[ 0 13  1  3  5 12 15 

iteration1000  cost:6.497001147639499
iteration2000  cost:3.44708342999115
iteration3000  cost:3.109254469402843
iteration4000  cost:3.718461212492322
iteration5000  cost:2.529796809027322
iteration6000  cost:2.509917765436951
iteration7000  cost:3.6113032313050124


KeyboardInterrupt: 